version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: senha_do_usuario
    ports:
      - "3380:3380"
    volumes:
      - ./mysql_data:/var/lib/mysql

    